name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Check added SSH keys
      run: |
        ssh-add -L

    - name: Set Git SSH config
      run: |
        ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
        git config --global url."git@heroku.com:".insteadOf "https://git.heroku.com/"

    - name: Deploy to Heroku
      run: |
        git remote add heroku git@heroku.com:${{ env.HEROKU_APP_NAME }}.git
        git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: geodata-management
